### ISSUE TITLE
SplFileInfo Error 

### ISSUE THREAD

**Issue by MezaTech** [Vinelab/cdn#73]
while using 

php artisan cdn:push
after ( Uploading in progress... ) 
i got  
[ErrorException]                                                        
  Undefined property: Symfony\Component\Finder\SplFileInfo::$getRealpath

**Comment by olimorris** [comment]
I got this error in v1.1.6. This was fixed in #72 and when @Mulkave has corrected build tests this will be tagged to v1.1.7

**Comment by MezaTech** [comment]
@olimorris  this error still appears in latest version which merged  yesterday , not solved till now 
Thanks

**Comment by olimorris** [comment]
Could you share your CDN config file settings? Difficult to know why the exception may be occuring

**Comment by Mahmoudz** [comment]
@MezaTech I have created the release `v1.1.7` you can try now.

**Comment by Mahmoudz** [comment]
@MezaTech This problem was solved (on release v1.2.0), please test it when you can.
Now you will get a full error details instead of this wired error if you have anything wrong with your new configurations.
If it happened and you get and error similar to this one: `AWS HTTP error: cURL error 6: Could not resolve host...` that means the `region` you are using is incorrect, so just choose another one and push again.

**Comment by olimorris** [comment]
@Mahmoudz I suspected this was the case. Great work. This is a super package once again.

@MezaTech in future, share as much of your code as you can. Just pasting the error message doesn't help. Always share your config file as that is likely where you have edited things and introduced errors into the package yourself.
